"""add_trigger_source_and_llm_raw_output

Revision ID: 99c6c81aed9f
Revises: 001
Create Date: 2026-04-09 21:20:17.722436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c6c81aed9f'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_logs', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('HUNTER', 'ASSISTANT', name='conversationrole'),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_conversation_logs_project_id'))

    with op.batch_alter_table('project_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger_source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('llm_raw_output', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'RECOMMENDED', 'ELIMINATED', 'INTERVIEWED', 'FAILED', name='projectcandidatestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_index(batch_op.f('ix_project_candidates_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_project_candidates_project_id'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('mode',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PRECISE', 'EXPLORE', name='projectmode'),
               existing_nullable=False,
               existing_server_default=sa.text("'precise'"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', name='projectstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', name='projectstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('mode',
               existing_type=sa.Enum('PRECISE', 'EXPLORE', name='projectmode'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'precise'"))

    with op.batch_alter_table('project_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_candidates_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_candidates_candidate_id'), ['candidate_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'RECOMMENDED', 'ELIMINATED', 'INTERVIEWED', 'FAILED', name='projectcandidatestatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_column('llm_raw_output')
        batch_op.drop_column('trigger_source')

    with op.batch_alter_table('conversation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_logs_project_id'), ['project_id'], unique=False)
        batch_op.alter_column('role',
               existing_type=sa.Enum('HUNTER', 'ASSISTANT', name='conversationrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
